### ISSUE TITLE
Error while \quit

### ISSUE THREAD

**Issue by Ar4ikcs** [tarantool/cartridge-cli#729] opened 2022-07-13 08:04 UTC
devteam-7041-003.s1-master> \quit
   ⨯ Whoops! It looks like something is wrong with this version of Cartridge CLI.
Please, report a bug at https://github.com/tarantool/cartridge-cli/issues/new.
Error: Unhandled internal error: runtime error: index out of range [0] with length 0
Version: Tarantool Cartridge CLI
 Version:       2.12.2
 OS/Arch:       linux/amd64
 Git commit:    53e6a5b

Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/debug/stack.go:24 +0x65
github.com/tarantool/cartridge-cli/cli/project.InternalError({0xae4244?, 0x0?}, {0xc0001c9820?, 0xc0001c9818?, 0xc0001c9818?})
        /home/runner/work/cartridge-cli/cartridge-cli/cli/project/project.go:118 +0x59
main.main.func1()
        /home/runner/work/cartridge-cli/cartridge-cli/cli/main.go:13 +0x5c
panic({0xa9a840, 0xc000028138})
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/panic.go:838 +0x207
github.com/tarantool/cartridge-cli/cli/connect.getExecutor.func1({0xc0003c4320?, 0x0?})
        /home/runner/work/cartridge-cli/cartridge-cli/cli/connect/console.go:216 +0x3ab
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0004cb540)
        /home/runner/go/pkg/mod/github.com/tarantool/go-prompt@v0.2.6-tarantool/prompt.go:91 +0x771
github.com/tarantool/cartridge-cli/cli/connect.(*Console).Run(0xc0004de0b0)
        /home/runner/work/cartridge-cli/cartridge-cli/cli/connect/console.go:136 +0x17f
github.com/tarantool/cartridge-cli/cli/connect.runConsole(0x7ffd6c374545?, {0x0?, 0xfb97c0?})
        /home/runner/work/cartridge-cli/cartridge-cli/cli/connect/connect.go:81 +0xbd
github.com/tarantool/cartridge-cli/cli/connect.Connect(0xc0004ba700?, {0xc000058670?, 0xc00025fd68?, 0xc00025fd40?})
        /home/runner/work/cartridge-cli/cartridge-cli/cli/connect/connect.go:66 +0x8c
github.com/tarantool/cartridge-cli/cli/commands.init.5.func2(0xc0004b5080?, {0xc000058670?, 0x1?, 0x1?})
        /home/runner/work/cartridge-cli/cartridge-cli/cli/commands/connect.go:36 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0004b5080, {0xc000058650, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200815144417-81e0311edd0b/command.go:846 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xfb01c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200815144417-81e0311edd0b/command.go:950 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200815144417-81e0311edd0b/command.go:887
github.com/tarantool/cartridge-cli/cli/commands.Execute()
        /home/runner/work/cartridge-cli/cartridge-cli/cli/commands/cartridge.go:48 +0x25
main.main()
        /home/runner/work/cartridge-cli/cartridge-cli/cli/main.go:17 +0x3b

**Comment by Ar4ikcs** [comment] 2022-07-13 08:04
After that error i can't type any in terminal

**Comment by LeonidVas** [comment] 2022-08-18 08:40
Duplicate of #705

**Closed by LeonidVas** 2022-08-18 08:40 UTC
Labels: bug
