### ISSUE TITLE
Do not force semver use for cartridge apps

### ISSUE THREAD

**Issue by nvkv** [tarantool/cartridge-cli#522] opened 2021-03-26 09:22 UTC
For reasons completely outside of the scope of this ticket it's not acceptable for us to use Semantic Versioning. 

But cartridge-cli was [specifically designed to force semver](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_dev/#application-versioning). It would be nice to have a way to bypass this somewhat dubious rule.

Example:

```sh
% cartridge version
Tarantool Cartridge CLI v2.7.2 linux/amd64 commit: fde10b1
% cartridge pack tgz --version=v1-2021.03.26 |& dumb
   • Packing foods into tgz   
   ⨯ Version should be semantic (major.minor.patch[-count][-commit])
```

**Comment by RunsFor** [comment] 2021-04-13 17:22
duplicate of #475

**Comment by Totktonada** [comment] 2021-07-23 15:02
Closing as duplicate of #475.

**Closed by Totktonada** 2021-07-23 15:02 UTC
